# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-08f503b9-ca4a-47f5-b33c-cd8e45b9a515";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-08f503b9-ca4a-47f5-b33c-cd8e45b9a515".device = "/dev/disk/by-uuid/08f503b9-ca4a-47f5-b33c-cd8e45b9a515";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A643-B8C6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a19c78a0-1aa5-4d57-b476-dfccf90cadf1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
